### ISSUE TITLE
What License is this under? 

### ISSUE THREAD

**Issue by sirhcsenots** [trebonian/visual6502#37]
It uses 3rd party GPL Code so I assume GPL. But it is not actually officially stated. 
The website didn't mention it either or it was confusing. 

Thanks for your time. 

~Chris

**Comment by BigEd** [comment]
Here's my opinion: I think you'll find all the source files have an MIT-style license header. There are two 3rd party files which are both dual-licensed (GPL and MIT) and so here they could be considered MIT licensed too.
