### ISSUE TITLE
SVG missing clock phase 1

### ISSUE THREAD

**Issue by deephooloovoo** [trebonian/visual6502#51]
I am planning to plot this with my HP pen plotter, and I'd like to plot each layer of silicon separately. The svg branch appears to have the only SVG file with all the layers separated. Unfortunately, it is missing at least one trace, clock phase 1.

**Comment by BigEd** [comment]
You should be able to see node 710, cp1 (as well as node 943, cclk)

There's a version of visual6502 which uses the SVG here:
https://biged.github.io/visual6502/

**Comment by deephooloovoo** [comment]
Almost all of the metal layer for cp1 is missing. All other layers appear at first glance to be complete. The only part which does appear to exist is near the top of the chip. The approximate location of the missing metal is highlighted
![missing-cp1](https://user-images.githubusercontent.com/3269335/43729944-7beadc2e-996f-11e8-8078-132bc704614e.png)

**Comment by BigEd** [comment]
I think there is no cp1 there, so there is nothing missing - have you compared the SVG version with the canvas version? I've just loaded both up, and clicked on the cp1 node, and I see the same chip-wide shapes highlighted.

If you do find a piece which is missing, please do share!

**Comment by deephooloovoo** [comment]
If I zoom in and select cp1 in the SVG version, it is highlighted, and appears correctly, however it appears as if the highlights are drawn from the paths in segdefs.js, not the SVG. When cp1 is not highlighted, there is nothing there.

**Comment by BigEd** [comment]
Aha - I see what you mean! Sorry for being slow. Let me check with the others.

**Comment by BigEd** [comment]
Hi @deephooloovoo I've found some other 6502 SVG files which are I think upstream of the ones in the visual6502 'svg' fork: I think we can see more tracks in them, at least.

https://github.com/pmonta/FPGA-netlist-tools/tree/master/masks/6502

**Comment by deephooloovoo** [comment]
That's exactly what I needed, thanks!
