### ISSUE TITLE
[bug] 6502 address 0xD011 can't be read from

### ISSUE THREAD

**Issue by rijenkii** [trebonian/visual6502#61]
http://www.visual6502.org/JSSim/expert.html?graphics=false&steps=22&a=0&d=a9698d11d0ad11d0ea

asm:
```
LDA #$69
STA $D011
LDA $D011
NOP
```

After execution (cycle 10) `a` must be 69, but it's 0

**Comment by BigEd** [comment]
Oops!  Indeed, there are a couple of demonstration triggers defined in
http://www.visual6502.org/JSSim/testprogram.js
which in effect make d010 and d011 into an input port which reads the console:
```
// demonstrate read hook (not used by this test program)
readTriggers[0xD011]="((consolegetc==undefined)?0:0xff)";  // return zero until we have a char
readTriggers[0xD010]="var c=consolegetc; consolegetc=undefined; (c)";
```

I've a feeling we will have used these features in various published URLs, so we can't just remove the feature.

Indeed, it's documented here
http://visual6502.org/wiki/index.php?title=JssimUserHelp#Interacting_with_the_program

**Comment by rijenkii** [comment]
Ah, so it's intended behavior.
If I'm understanding correctly, it can be disabled on a local copy of the repo by just removing these two lines from `testprogram.js`?

**Comment by BigEd** [comment]
Yes, that would do it. Or, from the console, just re-empty the list of triggers:
readTriggers={};

**Comment by rijenkii** [comment]
Thanks! Guess I'll close this issue then
